In [ ]:
pip install pandas openpyxl matplotlib seaborn

Requirement already satisfied: pandas in /usr/local/lib/python3.12/dist-packages (2.2.2)
Requirement already satisfied: openpyxl in /usr/local/lib/python3.12/dist-packages (3.1.5)
Requirement already satisfied: matplotlib in /usr/local/lib/python3.12/dist-packages (3.10.0)
Requirement already satisfied: seaborn in /usr/local/lib/python3.12/dist-packages (0.13.2)
Requirement already satisfied: numpy>=1.26.0 in /usr/local/lib/python3.12/dist-packages (from pandas) (2.0.2)
Requirement already satisfied: python-dateutil>=2.8.2 in /usr/local/lib/python3.12/dist-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.12/dist-packages (from pandas) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in /usr/local/lib/python3.12/dist-packages (from pandas) (2026.2)
Requirement already satisfied: et-xmlfile in /usr/local/lib/python3.12/dist-packages (from openpyxl) (2.0.0)
Requirement already satisfied: contourpy>=1.0.1 in /usr/local/lib/python3.12/dist-packages (from matplotlib) (1.3.3)
Requirement already satisfied: cycler>=0.10 in /usr/local/lib/python3.12/dist-packages (from matplotlib) (0.12.1)
Requirement already satisfied: fonttools>=4.22.0 in /usr/local/lib/python3.12/dist-packages (from matplotlib) (4.63.0)
Requirement already satisfied: kiwisolver>=1.3.1 in /usr/local/lib/python3.12/dist-packages (from matplotlib) (1.5.0)
Requirement already satisfied: packaging>=20.0 in /usr/local/lib/python3.12/dist-packages (from matplotlib) (26.2)
Requirement already satisfied: pillow>=8 in /usr/local/lib/python3.12/dist-packages (from matplotlib) (11.3.0)
Requirement already satisfied: pyparsing>=2.3.1 in /usr/local/lib/python3.12/dist-packages (from matplotlib) (3.3.2)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.12/dist-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)

In [2]:
import pandas as pd

df=pd.read_excel(
    "/content/Bank_Credit_Deposit_Analysis.xlsx",
    sheet_name="Master_Data"
)
df.head()

,Region/State/Union Territory,Deposit,Unnamed: 2,Unnamed: 3,Unnamed: 4,Unnamed: 5,Unnamed: 6,Credit,Unnamed: 8,Unnamed: 9,Unnamed: 10,Unnamed: 11,Unnamed: 12
0,-1,2020,2021,2022,2023,2024,2025,2020,2021,2022,2023,2024,2025
1,NaN,-2,-3,-4,-5,-6,-7,-8,-9,-10,-11,-12,-13
2,Haryana,475352,538565,614014,702370,788798,888772,260619,287499,372955,411060,525579,607750
3,Himachal Pradesh,103545,112344,123672,136486,150334,162531,31306,34770,40942,45325,53601,61409
4,Jammu & Kashmir,128026,142897,153229,162908,175967,191982,58663,69302,79961,90525,102722,109193

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 39 entries, 0 to 38
Data columns (total 13 columns):
 #   Column                        Non-Null Count  Dtype
---  ------                        --------------  -----
 0   Region/State/Union Territory  38 non-null     object
 1   Deposit                       39 non-null     object
 2   Unnamed: 2                    39 non-null     object
 3   Unnamed: 3                    39 non-null     object
 4   Unnamed: 4                    39 non-null     object
 5   Unnamed: 5                    39 non-null     object
 6   Unnamed: 6                    39 non-null     object
 7   Credit                        39 non-null     object
 8   Unnamed: 8                    39 non-null     object
 9   Unnamed: 9                    39 non-null     object
 10  Unnamed: 10                   39 non-null     object
 11  Unnamed: 11                   39 non-null     object
 12  Unnamed: 12                   39 non-null     object
dtypes: object(13)
memory usage: 4.1+ KB

In [ ]:
print(df.columns.tolist())

['Region/State/Union Territory', 'Deposit', 'Unnamed: 2', 'Unnamed: 3', 'Unnamed: 4', 'Unnamed: 5', 'Unnamed: 6', 'Credit', 'Unnamed: 8', 'Unnamed: 9', 'Unnamed: 10', 'Unnamed: 11', 'Unnamed: 12']

In [ ]:
df.columns = [
    "State",
    "Deposit_2020", "Deposit_2021", "Deposit_2022", "Deposit_2023", "Deposit_2024", "Deposit_2025",
    "Credit_2020", "Credit_2021", "Credit_2022", "Credit_2023", "Credit_2024", "Credit_2025"
]

df.head()

,State,Deposit_2020,Deposit_2021,Deposit_2022,Deposit_2023,Deposit_2024,Deposit_2025,Credit_2020,Credit_2021,Credit_2022,Credit_2023,Credit_2024,Credit_2025
0,-1,2020,2021,2022,2023,2024,2025,2020,2021,2022,2023,2024,2025
1,NaN,-2,-3,-4,-5,-6,-7,-8,-9,-10,-11,-12,-13
2,Haryana,475352,538565,614014,702370,788798,888772,260619,287499,372955,411060,525579,607750
3,Himachal Pradesh,103545,112344,123672,136486,150334,162531,31306,34770,40942,45325,53601,61409
4,Jammu & Kashmir,128026,142897,153229,162908,175967,191982,58663,69302,79961,90525,102722,109193

In [ ]:
# keep only valid state rows
df = df[df["State"].notna()]
df = df[df["State"].astype(str).str.strip() != ""]
df = df[df["State"].astype(str).str.strip() != "-1"]

df.reset_index(drop=True, inplace=True)
df.head()

,State,Deposit_2020,Deposit_2021,Deposit_2022,Deposit_2023,Deposit_2024,Deposit_2025,Credit_2020,Credit_2021,Credit_2022,Credit_2023,Credit_2024,Credit_2025
0,Haryana,475352,538565,614014,702370,788798,888772,260619,287499,372955,411060,525579,607750
1,Himachal Pradesh,103545,112344,123672,136486,150334,162531,31306,34770,40942,45325,53601,61409
2,Jammu & Kashmir,128026,142897,153229,162908,175967,191982,58663,69302,79961,90525,102722,109193
3,Punjab,410987,459027,510138,560275,617489,668830,234738,252685,288331,300770,360008,391262
4,Rajasthan,420150,474438,530634,594426,670970,741436,334449,369374,442730,485098,581568,656903

In [ ]:
deposit_long = df.melt(
    id_vars="State",
    value_vars=["Deposit_2020", "Deposit_2021", "Deposit_2022", "Deposit_2023", "Deposit_2024", "Deposit_2025"],
    var_name="Year",
    value_name="Deposit"
)

credit_long = df.melt(
    id_vars="State",
    value_vars=["Credit_2020", "Credit_2021", "Credit_2022", "Credit_2023", "Credit_2024", "Credit_2025"],
    var_name="Year",
    value_name="Credit"
)

In [ ]:
deposit_long["Year"] = deposit_long["Year"].str.replace("Deposit_", "")
credit_long["Year"] = credit_long["Year"].str.replace("Credit_", "")

In [ ]:
banking_long = pd.merge(
    deposit_long,
    credit_long,
    on=["State", "Year"]
)

banking_long.head(10)

               State  Year  Deposit   Credit
0            Haryana  2020   475352   260619
1   Himachal Pradesh  2020   103545    31306
2    Jammu & Kashmir  2020   128026    58663
3             Punjab  2020   410987   234738
4          Rajasthan  2020   420150   334449
5         Chandigarh  2020    72552    78690
6              Delhi  2020  1238245  1365110
7             Ladakh  2020     4955     1791
8  Arunachal Pradesh  2020    17171     4277
9              Assam  2020   164299    70625

In [ ]:
banking_long.shape

(222, 4)

In [ ]:
# remove blank state rows if any
banking_long = banking_long[banking_long["State"].notna()]

# remove rows where State is empty string
banking_long = banking_long[banking_long["State"].astype(str).str.strip() != ""]

# clean Year column and convert to integer
banking_long["Year"] = banking_long["Year"].astype(int)

# convert Deposit and Credit to numeric
banking_long["Deposit"] = pd.to_numeric(banking_long["Deposit"], errors="coerce")
banking_long["Credit"] = pd.to_numeric(banking_long["Credit"], errors="coerce")

# drop rows where Deposit or Credit is missing
banking_long = banking_long.dropna(subset=["Deposit", "Credit"])

# reset index
banking_long = banking_long.reset_index(drop=True)

banking_long.head()

              State  Year   Deposit    Credit
0           Haryana  2020  475352.0  260619.0
1  Himachal Pradesh  2020  103545.0   31306.0
2   Jammu & Kashmir  2020  128026.0   58663.0
3            Punjab  2020  410987.0  234738.0
4         Rajasthan  2020  420150.0  334449.0

In [ ]:
banking_long.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 216 entries, 0 to 215
Data columns (total 4 columns):
 #   Column   Non-Null Count  Dtype
---  ------   --------------  -----
 0   State    216 non-null    object
 1   Year     216 non-null    int64
 2   Deposit  216 non-null    float64
 3   Credit   216 non-null    float64
dtypes: float64(2), int64(1), object(1)
memory usage: 6.9+ KB

In [ ]:
banking_long.shape

(216, 4)

In [ ]:
banking_long.head()

              State  Year   Deposit    Credit
0           Haryana  2020  475352.0  260619.0
1  Himachal Pradesh  2020  103545.0   31306.0
2   Jammu & Kashmir  2020  128026.0   58663.0
3            Punjab  2020  410987.0  234738.0
4         Rajasthan  2020  420150.0  334449.0

In [ ]:
banking_long.tail()

           State  Year    Deposit     Credit
211       Kerala  2025   894855.0   615615.0
212   Tamil Nadu  2025  1463026.0  1687805.0
213  Lakshadweep  2025     1540.0      195.0
214   Puducherry  2025    32927.0    23693.0
215    Telangana  2025   867571.0   968183.0

In [ ]:
banking_long.groupby("Year")["Credit"].sum()

Year
2020    10518815.0
2021    11078049.0
2022    12258747.0
2023    14198008.0
2024    16913695.0
2025    18786865.0
Name: Credit, dtype: float64

In [ ]:
banking_long[banking_long["Year"] == 2025]

                         State  Year    Deposit     Credit
180                    Haryana  2025   888772.0   607750.0
181           Himachal Pradesh  2025   162531.0    61409.0
182            Jammu & Kashmir  2025   191982.0   109193.0
183                     Punjab  2025   668830.0   391262.0
184                  Rajasthan  2025   741436.0   656903.0
185                 Chandigarh  2025   126596.0    91035.0
186                      Delhi  2025  2071013.0  1900568.0
187                     Ladakh  2025     9885.0     4277.0
188          Arunachal Pradesh  2025    33114.0    10273.0
189                      Assam  2025   234070.0   146867.0
190                    Manipur  2025    16806.0    12866.0
191                  Meghalaya  2025    37779.0    15241.0
192                    Mizoram  2025    17462.0     8987.0
193                   Nagaland  2025    18789.0     9792.0
194                    Tripura  2025    42140.0    18224.0
195                      Bihar  2025   568726.0   292274.0
196                  Jharkhand  2025   367362.0   144525.0
197                     Odisha  2025   583925.0   281088.0
198                     Sikkim  2025    16290.0     7067.0
199                West Bengal  2025  1225284.0   632168.0
200  Andaman & Nicobar Islands  2025     8549.0     4463.0
201               Chhattisgarh  2025   268161.0   213314.0
202             Madhya Pradesh  2025   673476.0   527588.0
203              Uttar Pradesh  2025  1909885.0   972486.0
204                Uttarakhand  2025   246010.0   102097.0
205                        Goa  2025   120662.0    32244.0
206                    Gujarat  2025  1273072.0  1014466.0
207                Maharashtra  2025  5233966.0  5135539.0
208       Dadra & Nagar Haveli  2025    16965.0     7625.0
209             Andhra Pradesh  2025   529673.0   800238.0
210                  Karnataka  2025  1888708.0  1279545.0
211                     Kerala  2025   894855.0   615615.0
212                 Tamil Nadu  2025  1463026.0  1687805.0
213                Lakshadweep  2025     1540.0      195.0
214                 Puducherry  2025    32927.0    23693.0
215                  Telangana  2025   867571.0   968183.0

In [ ]:
banking_long["CD_Ratio"] = banking_long["Credit"] / banking_long["Deposit"] * 100
banking_long.head()

              State  Year   Deposit    Credit   CD_Ratio
0           Haryana  2020  475352.0  260619.0  54.826529
1  Himachal Pradesh  2020  103545.0   31306.0  30.234198
2   Jammu & Kashmir  2020  128026.0   58663.0  45.821161
3            Punjab  2020  410987.0  234738.0  57.115675
4         Rajasthan  2020  420150.0  334449.0  79.602285

In [ ]:
sorted(banking_long["State"].unique())

['Andaman & Nicobar Islands',
 'Andhra Pradesh',
 'Arunachal Pradesh',
 'Assam',
 'Bihar',
 'Chandigarh',
 'Chhattisgarh',
 'Dadra & Nagar Haveli',
 'Delhi',
 'Goa',
 'Gujarat',
 'Haryana',
 'Himachal Pradesh',
 'Jammu & Kashmir',
 'Jharkhand',
 'Karnataka',
 'Kerala',
 'Ladakh',
 'Lakshadweep',
 'Madhya Pradesh',
 'Maharashtra',
 'Manipur',
 'Meghalaya',
 'Mizoram',
 'Nagaland',
 'Odisha',
 'Puducherry',
 'Punjab',
 'Rajasthan',
 'Sikkim',
 'Tamil Nadu',
 'Telangana',
 'Tripura',
 'Uttar Pradesh',
 'Uttarakhand',
 'West Bengal']

In [ ]:
# make sure data types are correct
banking_long["Year"] = banking_long["Year"].astype(int)
banking_long["Deposit"] = pd.to_numeric(banking_long["Deposit"], errors="coerce")
banking_long["Credit"] = pd.to_numeric(banking_long["Credit"], errors="coerce")

# remove rows where Deposit or Credit is missing
banking_long = banking_long.dropna(subset=["Deposit", "Credit"]).reset_index(drop=True)

# optional: convert to integer if you don't want decimals like 475352.0
banking_long["Deposit"] = banking_long["Deposit"].astype(int)
banking_long["Credit"] = banking_long["Credit"].astype(int)

# preview
banking_long.head()

              State  Year  Deposit  Credit   CD_Ratio
0           Haryana  2020   475352  260619  54.826529
1  Himachal Pradesh  2020   103545   31306  30.234198
2   Jammu & Kashmir  2020   128026   58663  45.821161
3            Punjab  2020   410987  234738  57.115675
4         Rajasthan  2020   420150  334449  79.602285

In [ ]:
region_map = {
    "Haryana": "Northern",
    "Himachal Pradesh": "Northern",
    "Jammu & Kashmir": "Northern",
    "Punjab": "Northern",
    "Rajasthan": "Northern",
    "Chandigarh": "Northern",
    "Delhi": "Northern",
    "Ladakh": "Northern",

    "Arunachal Pradesh": "North-Eastern",
    "Assam": "North-Eastern",
    "Manipur": "North-Eastern",
    "Meghalaya": "North-Eastern",
    "Mizoram": "North-Eastern",
    "Nagaland": "North-Eastern",
    "Tripura": "North-Eastern",

    "Bihar": "Eastern",
    "Jharkhand": "Eastern",
    "Odisha": "Eastern",
    "Sikkim": "Eastern",
    "West Bengal": "Eastern",
    "Andaman & Nicobar Islands": "Eastern",

    "Chhattisgarh": "Central",
    "Madhya Pradesh": "Central",
    "Uttar Pradesh": "Central",
    "Uttarakhand": "Central",

    "Goa": "Western",
    "Gujarat": "Western",
    "Maharashtra": "Western",
    "Dadra & Nagar Haveli": "Western",

    "Andhra Pradesh": "Southern",
    "Karnataka": "Southern",
    "Kerala": "Southern",
    "Tamil Nadu": "Southern",
    "Telangana": "Southern",
    "Puducherry": "Southern",
    "Lakshadweep": "Southern"
}

banking_long["Region"] = banking_long["State"].map(region_map)

banking_long.head()

              State  Year  Deposit  Credit   CD_Ratio    Region
0           Haryana  2020   475352  260619  54.826529  Northern
1  Himachal Pradesh  2020   103545   31306  30.234198  Northern
2   Jammu & Kashmir  2020   128026   58663  45.821161  Northern
3            Punjab  2020   410987  234738  57.115675  Northern
4         Rajasthan  2020   420150  334449  79.602285  Northern

In [ ]:
banking_long = banking_long[["Year", "Region", "State", "Deposit", "Credit"]]
banking_long.head()

   Year    Region             State  Deposit  Credit
0  2020  Northern           Haryana   475352  260619
1  2020  Northern  Himachal Pradesh   103545   31306
2  2020  Northern   Jammu & Kashmir   128026   58663
3  2020  Northern            Punjab   410987  234738
4  2020  Northern         Rajasthan   420150  334449

In [ ]:
banking_long.to_csv("banking_clean.csv", index=False, encoding="utf-8")
print("Real CSV created successfully!")

Real CSV created successfully!

In [ ]:
from google.colab import files
files.download("banking_clean.csv")